In [33]:
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import string

In [13]:
df = pd.read_csv('data/full_data_clean.csv')
df.head()

,Logische Periode,Endzeitstempel,Status,Tarif,location,adress,datetime,Wert,datetimeYear,datetimeMonth,datetimeWeek,datetimeDay,datetimeDayofweek,datetimeDayofyear,datetimeHour,datetimeMinute,datetimeSecond,datetimeElapsed
0,01.01.2019,07:00:00,N,,Bottroper Weg,"Bottroper Weg 8, 13507 Berlin",2019-01-01 07:00:00,0.0,2019,1,1,1,1,1,7,0,0,1546326000
1,01.01.2019,08:00:00,N,,Bottroper Weg,"Bottroper Weg 8, 13507 Berlin",2019-01-01 08:00:00,0.0,2019,1,1,1,1,1,8,0,0,1546329600
2,01.01.2019,09:00:00,N,,Bottroper Weg,"Bottroper Weg 8, 13507 Berlin",2019-01-01 09:00:00,0.0,2019,1,1,1,1,1,9,0,0,1546333200
3,01.01.2019,10:00:00,N,,Bottroper Weg,"Bottroper Weg 8, 13507 Berlin",2019-01-01 10:00:00,0.0,2019,1,1,1,1,1,10,0,0,1546336800
4,01.01.2019,11:00:00,N,,Bottroper Weg,"Bottroper Weg 8, 13507 Berlin",2019-01-01 11:00:00,0.0,2019,1,1,1,1,1,11,0,0,1546340400

In [14]:
df.columns

Index(['Logische Periode ', ' Endzeitstempel ', ' Status ', ' Tarif ',
       'location', 'adress', 'datetime', 'Wert', 'datetimeYear',
       'datetimeMonth', 'datetimeWeek', 'datetimeDay', 'datetimeDayofweek',
       'datetimeDayofyear', 'datetimeHour', 'datetimeMinute', 'datetimeSecond',
       'datetimeElapsed'],
      dtype='object')

In [34]:

locs = {}
def get_loc(loc):
    if not loc[0] in string.ascii_letters:
        loc = loc[5:]
    if loc in locs:
        return locs[loc]
    loc_url = loc.replace(',',' ').replace(' ','%20')
    response = requests.get('https://maps.googleapis.com/maps/api/geocode/json?address='+loc_url+'&key=AIzaSyDErx0jbn3Z9nkWw0zAod2ceJFqa8n7BiI')
    resp_json_payload = response.json()
    try:
        r= resp_json_payload['results'][0]['geometry']['location']
    except:
        print(loc,'not found')
        r= {'lat':0,'long':0}
    locs[loc] = r
    print(loc)
    print(locs)
    print()
    return r
def get_lat(loc):
    return get_loc(loc)['lat']
def get_lng(loc):
    return get_loc(loc)['lng']
    
get_loc('amsterdam')

amsterdam
{'amsterdam': {'lat': 52.3666969, 'lng': 4.8945398}}

{'lat': 52.3666969, 'lng': 4.8945398}

In [35]:
get_lat(df.loc[1,'adress'])
df['lat'] = df.adress.apply(get_lat)
df['long'] = df.adress.apply(get_lng)

Bottroper Weg 8, 13507 Berlin
{'amsterdam': {'lat': 52.3666969, 'lng': 4.8945398}, 'Bottroper Weg 8, 13507 Berlin': {'lat': 52.57697, 'lng': 13.28074}}

 Hamburg, Flughafenstr. 7412
{'amsterdam': {'lat': 52.3666969, 'lng': 4.8945398}, 'Bottroper Weg 8, 13507 Berlin': {'lat': 52.57697, 'lng': 13.28074}, ' Hamburg, Flughafenstr. 7412 ': {'lat': 53.629729, 'lng': 10.0082472}}

 Berlin, Joachim-Karnatz-Allee 43
{'amsterdam': {'lat': 52.3666969, 'lng': 4.8945398}, 'Bottroper Weg 8, 13507 Berlin': {'lat': 52.57697, 'lng': 13.28074}, ' Hamburg, Flughafenstr. 7412 ': {'lat': 53.629729, 'lng': 10.0082472}, ' Berlin, Joachim-Karnatz-Allee 43 ': {'lat': 52.5193516, 'lng': 13.3565023}}

 Hamburg, Lüttkamp 5
{'amsterdam': {'lat': 52.3666969, 'lng': 4.8945398}, 'Bottroper Weg 8, 13507 Berlin': {'lat': 52.57697, 'lng': 13.28074}, ' Hamburg, Flughafenstr. 7412 ': {'lat': 53.629729, 'lng': 10.0082472}, ' Berlin, Joachim-Karnatz-Allee 43 ': {'lat': 52.5193516, 'lng': 13.3565023}, ' Hamburg, Lüttkamp 5 ': {'lat': 53.5913122, 'lng': 9.8748462}}

 Hamburg, Ochsenweberstr. 25B
{'amsterdam': {'lat': 52.3666969, 'lng': 4.8945398}, 'Bottroper Weg 8, 13507 Berlin': {'lat': 52.57697, 'lng': 13.28074}, ' Hamburg, Flughafenstr. 7412 ': {'lat': 53.629729, 'lng': 10.0082472}, ' Berlin, Joachim-Karnatz-Allee 43 ': {'lat': 52.5193516, 'lng': 13.3565023}, ' Hamburg, Lüttkamp 5 ': {'lat': 53.5913122, 'lng': 9.8748462}, ' Hamburg, Ochsenweberstr. 25B ': {'lat': 53.67243999999999, 'lng': 10.0131853}}

Tharandter Str. 48, 01159 Dresden
{'amsterdam': {'lat': 52.3666969, 'lng': 4.8945398}, 'Bottroper Weg 8, 13507 Berlin': {'lat': 52.57697, 'lng': 13.28074}, ' Hamburg, Flughafenstr. 7412 ': {'lat': 53.629729, 'lng': 10.0082472}, ' Berlin, Joachim-Karnatz-Allee 43 ': {'lat': 52.5193516, 'lng': 13.3565023}, ' Hamburg, Lüttkamp 5 ': {'lat': 53.5913122, 'lng': 9.8748462}, ' Hamburg, Ochsenweberstr. 25B ': {'lat': 53.67243999999999, 'lng': 10.0131853}, 'Tharandter Str. 48, 01159 Dresden': {'lat': 51.0358965, 'lng': 13.7042316}}

 Berlin, Triftstr. 31
{'amsterdam': {'lat': 52.3666969, 'lng': 4.8945398}, 'Bottroper Weg 8, 13507 Berlin': {'lat': 52.57697, 'lng': 13.28074}, ' Hamburg, Flughafenstr. 7412 ': {'lat': 53.629729, 'lng': 10.0082472}, ' Berlin, Joachim-Karnatz-Allee 43 ': {'lat': 52.5193516, 'lng': 13.3565023}, ' Hamburg, Lüttkamp 5 ': {'lat': 53.5913122, 'lng': 9.8748462}, ' Hamburg, Ochsenweberstr. 25B ': {'lat': 53.67243999999999, 'lng': 10.0131853}, 'Tharandter Str. 48, 01159 Dresden': {'lat': 51.0358965, 'lng': 13.7042316}, ' Berlin, Triftstr. 31 ': {'lat': 52.5420303, 'lng': 13.3503816}}

Wilhelmsburger Str. 4, 20539 Hamburg
{'amsterdam': {'lat': 52.3666969, 'lng': 4.8945398}, 'Bottroper Weg 8, 13507 Berlin': {'lat': 52.57697, 'lng': 13.28074}, ' Hamburg, Flughafenstr. 7412 ': {'lat': 53.629729, 'lng': 10.0082472}, ' Berlin, Joachim-Karnatz-Allee 43 ': {'lat': 52.5193516, 'lng': 13.3565023}, ' Hamburg, Lüttkamp 5 ': {'lat': 53.5913122, 'lng': 9.8748462}, ' Hamburg, Ochsenweberstr. 25B ': {'lat': 53.67243999999999, 'lng': 10.0131853}, 'Tharandter Str. 48, 01159 Dresden': {'lat': 51.0358965, 'lng': 13.7042316}, ' Berlin, Triftstr. 31 ': {'lat': 52.5420303, 'lng': 13.3503816}, 'Wilhelmsburger Str. 4, 20539 Hamburg ': {'lat': 53.52809, 'lng': 10.0203599}}

In [38]:
df.groupby('location').head()

,Logische Periode,Endzeitstempel,Status,Tarif,location,adress,datetime,Wert,datetimeYear,datetimeMonth,datetimeWeek,datetimeDay,datetimeDayofweek,datetimeDayofyear,datetimeHour,datetimeMinute,datetimeSecond,datetimeElapsed,lat,long
0,01.01.2019,07:00:00,N,,Bottroper Weg,"Bottroper Weg 8, 13507 Berlin",2019-01-01 07:00:00,0.000,2019,1,1,1,1,1,7,0,0,1546326000,52.576970,13.280740
1,01.01.2019,08:00:00,N,,Bottroper Weg,"Bottroper Weg 8, 13507 Berlin",2019-01-01 08:00:00,0.000,2019,1,1,1,1,1,8,0,0,1546329600,52.576970,13.280740
2,01.01.2019,09:00:00,N,,Bottroper Weg,"Bottroper Weg 8, 13507 Berlin",2019-01-01 09:00:00,0.000,2019,1,1,1,1,1,9,0,0,1546333200,52.576970,13.280740
3,01.01.2019,10:00:00,N,,Bottroper Weg,"Bottroper Weg 8, 13507 Berlin",2019-01-01 10:00:00,0.000,2019,1,1,1,1,1,10,0,0,1546336800,52.576970,13.280740
4,01.01.2019,11:00:00,N,,Bottroper Weg,"Bottroper Weg 8, 13507 Berlin",2019-01-01 11:00:00,0.000,2019,1,1,1,1,1,11,0,0,1546340400,52.576970,13.280740
5927,01.01.2019,07:00:00,N,,Flughafenstr.,"22415 Hamburg, Flughafenstr. 7412",2019-01-01 07:00:00,0.000,2019,1,1,1,1,1,7,0,0,1546326000,53.629729,10.008247
5928,01.01.2019,08:00:00,N,,Flughafenstr.,"22416 Hamburg, Flughafenstr. 7412",2019-01-01 08:00:00,0.000,2019,1,1,1,1,1,8,0,0,1546329600,53.629729,10.008247
5929,01.01.2019,09:00:00,N,,Flughafenstr.,"22417 Hamburg, Flughafenstr. 7412",2019-01-01 09:00:00,0.000,2019,1,1,1,1,1,9,0,0,1546333200,53.629729,10.008247
5930,01.01.2019,10:00:00,N,,Flughafenstr.,"22418 Hamburg, Flughafenstr. 7412",2019-01-01 10:00:00,0.000,2019,1,1,1,1,1,10,0,0,1546336800,53.629729,10.008247
5931,01.01.2019,11:00:00,N,,Flughafenstr.,"22419 Hamburg, Flughafenstr. 7412",2019-01-01 11:00:00,0.000,2019,1,1,1,1,1,11,0,0,1546340400,53.629729,10.008247
11854,01.01.2019,07:00:00,N,,Joachim-Karnatz-Allee,"10557 Berlin, Joachim-Karnatz-Allee 43",2019-01-01 07:00:00,0.000,2019,1,1,1,1,1,7,0,0,1546326000,52.519352,13.356502
11855,01.01.2019,08:00:00,N,,Joachim-Karnatz-Allee,"10558 Berlin, Joachim-Karnatz-Allee 43",2019-01-01 08:00:00,0.000,2019,1,1,1,1,1,8,0,0,1546329600,52.519352,13.356502
11856,01.01.2019,09:00:00,N,,Joachim-Karnatz-Allee,"10559 Berlin, Joachim-Karnatz-Allee 43",2019-01-01 09:00:00,0.000,2019,1,1,1,1,1,9,0,0,1546333200,52.519352,13.356502
11857,01.01.2019,10:00:00,N,,Joachim-Karnatz-Allee,"10560 Berlin, Joachim-Karnatz-Allee 43",2019-01-01 10:00:00,0.000,2019,1,1,1,1,1,10,0,0,1546336800,52.519352,13.356502
11858,01.01.2019,11:00:00,N,,Joachim-Karnatz-Allee,"10561 Berlin, Joachim-Karnatz-Allee 43",2019-01-01 11:00:00,0.000,2019,1,1,1,1,1,11,0,0,1546340400,52.519352,13.356502
17781,01.01.2019,07:00:00,N,,Lüttkamp,"22547 Hamburg, Lüttkamp 5",2019-01-01 07:00:00,0.000,2019,1,1,1,1,1,7,0,0,1546326000,53.591312,9.874846
17782,01.01.2019,08:00:00,N,,Lüttkamp,"22548 Hamburg, Lüttkamp 5",2019-01-01 08:00:00,0.000,2019,1,1,1,1,1,8,0,0,1546329600,53.591312,9.874846
17783,01.01.2019,09:00:00,N,,Lüttkamp,"22549 Hamburg, Lüttkamp 5",2019-01-01 09:00:00,0.000,2019,1,1,1,1,1,9,0,0,1546333200,53.591312,9.874846
17784,01.01.2019,10:00:00,N,,Lüttkamp,"22550 Hamburg, Lüttkamp 5",2019-01-01 10:00:00,0.000,2019,1,1,1,1,1,10,0,0,1546336800,53.591312,9.874846
17785,01.01.2019,11:00:00,N,,Lüttkamp,"22551 Hamburg, Lüttkamp 5",2019-01-01 11:00:00,0.000,2019,1,1,1,1,1,11,0,0,1546340400,53.591312,9.874846
23708,01.01.2019,07:00:00,N,,Ochsenweberstr.,"22149 Hamburg, Ochsenweberstr. 25B",2019-01-01 07:00:00,0.000,2019,1,1,1,1,1,7,0,0,1546326000,53.672440,10.013185
23709,01.01.2019,08:00:00,N,,Ochsenweberstr.,"22150 Hamburg, Ochsenweberstr. 25B",2019-01-01 08:00:00,0.000,2019,1,1,1,1,1,8,0,0,1546329600,53.672440,10.013185
23710,01.01.2019,09:00:00,N,,Ochsenweberstr.,"22151 Hamburg, Ochsenweberstr. 25B",2019-01-01 09:00:00,0.000,2019,1,1,1,1,1,9,0,0,1546333200,53.672440,10.013185
23711,01.01.2019,10:00:00,N,,Ochsenweberstr.,"22152 Hamburg, Ochsenweberstr. 25B",2019-01-01 10:00:00,0.000,2019,1,1,1,1,1,10,0,0,1546336800,53.672440,10.013185
23712,01.01.2019,11:00:00,N,,Ochsenweberstr.,"22153 Hamburg, Ochsenweberstr. 25B",2019-01-01 11:00:00,0.000,2019,1,1,1,1,1,11,0,0,1546340400,53.672440,10.013185
29635,01.01.2019,07:00:00,W,tariflos,Tharandter Str.,"Tharandter Str. 48, 01159 Dresden",2019-01-01 07:00:00,96.763,2019,1,1,1,1,1,7,0,0,1546326000,51.035896,13.704232
29636,01.01.2019,08:00:00,W,tariflos,Tharandter Str.,"Tharandter Str. 48, 01159 Dresden",2019-01-01 08:00:00,67.727,2019,1,1,1,1,1,8,0,0,1546329600,51.035896,13.704232
29637,01.01.2019,09:00:00,W,tariflos,Tharandter Str.,"Tharandter Str. 48, 01159 Dresden",2019-01-01 09:00:00,73.106,2019,1,1,1,1,1,9,0,0,1546333200,51.035896,13.704232
29638,01.01.2019,10:00:00,W,tariflos,Tharandter Str.,"Tharandter Str. 48, 01159 Dresden",2019-01-01 10:00:00,76.328,2019,1,1,1,1,1,10,0,0,1546336800,51.035896,13.704232
29639,01.01.2019,11:00:00,W,tariflos,Tharandter Str.,"Tharandter Str. 48, 01159 Dresden",2019-01-01 11:00:00,82.784,2019,1,1,1,1,1,11,0,0,1546340400,51.035896,13.704232
35562,01.01.2019,07:00:00,N,,Triftstr.,"13128 Berlin, Triftstr. 31",2019-01-01 07:00:00,0.000,2019,1,1,1,1,1,7,0,0,1546326000,52.542030,13.350382
35563,01.01.2019,08:00:00,N,,Triftstr.,"13129 Berlin, Triftstr. 31",2019-01-01 08:00:00,0.000,2019,1,1,1,1,1,8,0,0,1546329600,52.542030,13.350382
35564,01.01.2019,09:00:00,N,,Triftstr.,"13130 Berlin, Triftstr. 31",2019-01-01 09:00:00,0.000,2019,1,1,1,1,1,9,0,0,1546333200,52.542030,13.350382
35565,01.01.2019,10:00:00,N,,Triftstr.,"13131 Berlin, Triftstr. 31",2019-01-01 10:00:00,0.000,2019,1,1,1,1,1,10,0,0,1546336800,52.542030,13.350382
35566,01.01.2019,11:00:00,N,,Triftstr.,"13132 Berlin, Triftstr. 31",2019-01-01 11:00:00,0.000,2019,1,1,1,1,1,11,0,0,1546340400,52.542030,13.350382
41489,01.01.2019,07:00:00,N,,Wilhelmsburger Str.,"Wilhelmsburger Str. 4, 20539 Hamburg",2019-01-01 07:00:00,0.000,2019,1,1,1,1,1,7,0,0,1546326000,53.528090,10.020360
41490,01.01.2019,08:00:00,N,,Wilhelmsburger Str.,"Wilhelmsburger Str. 4, 20539 Hamburg",2019-01-01 08:00:00,0.000,2019,1,1,1,1,1,8,0,0,1546329600,53.528090,10.020360
41491,01.01.2019,09:00:00,N,,Wilhelmsburger Str.,"Wilhelmsburger Str. 4, 20539 Hamburg",2019-01-01 09:00:00,0.000,2019,1,1,1,1,1,9,0,0,1546333200,53.528090,10.020360
41492,01.01.2019,10:00:00,N,,Wilhelmsburger Str.,"Wilhelmsburger Str. 4, 20539 Hamburg",2019-01-01 10:00:00,0.000,2019,1,1,1,1,1,10,0,0,1546336800,53.528090,10.020360
41493,01.01.2019,11:00:00,N,,Wilhelmsburger Str.,"Wilhelmsburger Str. 4, 20539 Hamburg",2019-01-01 11:00:00,0.000,2019,1,1,1,1,1,11,0,0,1546340400,53.528090,10.020360

In [39]:
df.to_csv('data/full_data_clean.csv',index=False)